### ISSUE TITLE
Botoexception thrown for replicated lambda@edge functions

### ISSUE THREAD

**Issue by danquack** [epsagon/clear-lambda-storage#3]
```
Deleting my-edge-function version 7
Traceback (most recent call last):
  File "clear_lambda_storage.py", line 160, in <module>
    remove_old_lambda_versions(PARSER.parse_args())
  File "clear_lambda_storage.py", line 125, in remove_old_lambda_versions
    FunctionName=version['FunctionArn']
  File "/private/tmp/clear-lambda-storage/venv/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/private/tmp/clear-lambda-storage/venv/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidParameterValueException: An error occurred (InvalidParameterValueException) when calling the DeleteFunction operation: Lambda was unable to delete arn:aws:lambda:us-east-1:redacted:function:my-edge-function:7 because it is a replicated function. Please see our documentation for Deleting Lambda@Edge Functions and Replicas.
```

**Comment by ranrib** [comment]
Fixed in https://github.com/epsagon/clear-lambda-storage/commit/37a45c632d9aceb430a1a392710eb3715e7bcc67
